version: '3.8'

services:
  localstack:
    container_name: localstack-ssrf
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # Puerto principal de LocalStack
    environment:
      - SERVICES=s3,ec2  # Habilitado EC2 y S3 (EC2, su etiqueta es basicamente la bandera) 
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIAAHAU7EXAMPLE12345
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7AHAUENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh  # Script de inicialización

  vulnerable-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


